name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-lint-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create google-service.json file
      run: cat /home/runner/work/Firebase-Auth-Blog/Firebase-Auth-Blog/app/google-services.json | base64

    - name: Insert data to google-service.json file
      env:
        DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA > /home/runner/work/Firebase-Auth-Blog/Firebase-Auth-Blog/app/google-services.json

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Lint Check
      run: ./gradlew lint

    - name: Save Lint Report
      uses: actions/upload-artifact@v1
      with:
        name: lint-result
        path: app/build/reports/lint-results-debug.html

    - name: Execute Unit Tests
      run: ./gradlew test

    - name: Save Unit Test Report
      uses: actions/upload-artifact@v1
      with:
        name: unit-test-result
        path: app/build/reports/tests/testDebugUnitTest/

